import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        serif: ["var(--font-serif)", "Playfair Display", "Georgia", "serif"],
        sans: ["var(--font-sans)", "Inter", "-apple-system", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "label-caps-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-xl-mobile": ["Playfair Display", "serif"],
        "subline-editorial": ["Playfair Display", "serif"],
        "label-caps-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "data-tabular": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.08em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "0.06em", fontWeight: "400" }],
        "label-caps-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.14em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-xl": ["44px", { lineHeight: "52px", letterSpacing: "0.12em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "0.08em", fontWeight: "400" }],
        "subline-editorial": ["18px", { lineHeight: "26px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-caps-md": ["13px", { lineHeight: "18px", letterSpacing: "0.12em", fontWeight: "600" }],
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "2.5rem",
        "space-22xl": "3rem",
        "space-3xl": "4rem",
        "card-margin-desktop": "3.5rem",
        "card-padding-desktop": "3rem",
        "card-margin-mobile": "1rem",
        "card-padding-mobile": "1.5rem",
      },
      colors: {
        lona: {
          gold: "#dfb15b",
          "gold-deep": "#c59b27",
          dark: "#04060a",
          surface: "#0e1522",
        },
        "obsidian-base": "#0A0A0C",
        "obsidian-elevated": "#18181B",
        "obsidian-bubble": "#1E1D1C",
        "canvas-outer": "#EFEEEC",
        "surface-container-lowest": "#0e0e11",
        "surface-container-low": "#1b1b1e",
        "surface-container": "#1f1f22",
        "surface-container-high": "#2a2a2d",
        "surface-container-highest": "#353438",
        "surface-bright": "#39393c",
        "surface-variant": "#353438",
        "surface-dim": "#131316",
        "surface": "#131316",
        "hairline-on-dark": "#2A2A2E",
        "hairline-on-light": "#DEDCD8",
        "text-on-light-primary": "#151415",
        "text-on-light-secondary": "#8A8884",
        "text-on-dark-primary": "#F5F4F1",
        "text-on-dark-secondary": "#9A9A9F",
        "state-success": "#8FAE97",
        "state-error": "#C77B6E",
        "tertiary": "#ffffff",
        "tertiary-fixed": "#dae4ed",
        "tertiary-container": "#dae4ed",
        "secondary-fixed": "#dfe3e8",
        "secondary-fixed-dim": "#c3c7cc",
        "secondary": "#c3c7cc",
        "on-surface": "#e4e1e6",
        "on-surface-variant": "#c4c7c4",
        "primary": "#ffffff",
        "on-primary": "#2f3130",
        "primary-container": "#e3e2e0",
        "on-primary-container": "#646463",
        "secondary-container": "#454a4e",
        "on-secondary-container": "#b5b9be",
        "outline": "#8e918f",
        "outline-variant": "#444845",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
    },
  },
  plugins: [],
};

export default config;
